/* eslint-disable linebreak-style */
export const keys = [
  { eng: '`', ru: 'ё', code: 'Backquote' },
  { eng: 'q', ru: 'й', code: 'KeyQ' },
  { eng: 'w', ru: 'ц', code: 'KeyW' },
  { eng: 'e', ru: 'у', code: 'KeyE' },
  { eng: 'r', ru: 'к', code: 'KeyR' },
  { eng: 't', ru: 'е', code: 'KeyT' },
  { eng: 'y', ru: 'н', code: 'KeyY' },
  { eng: 'u', ru: 'г', code: 'KeyU' },
  { eng: 'i', ru: 'ш', code: 'KeyI' },
  { eng: 'o', ru: 'щ', code: 'KeyO' },
  { eng: 'p', ru: 'з', code: 'KeyP' },
  { eng: '[{', ru: 'х', code: 'BracketLeft' },
  { eng: ']}', ru: 'ъ', code: 'BracketRight' },
  { eng: '\\|', ru: '\\/', code: 'Backslash' },
  { eng: 'a', ru: 'ф', code: 'KeyA' },
  { eng: 's', ru: 'ы', code: 'KeyS' },
  { eng: 'd', ru: 'в', code: 'KeyD' },
  { eng: 'f', ru: 'а', code: 'KeyF' },
  { eng: 'g', ru: 'п', code: 'KeyG' },
  { eng: 'h', ru: 'р', code: 'KeyH' },
  { eng: 'j', ru: 'о', code: 'KeyJ' },
  { eng: 'k', ru: 'л', code: 'KeyK' },
  { eng: 'l', ru: 'д', code: 'KeyL' },
  { eng: ';:', ru: 'ж', code: 'Semicolon' },
  { eng: "'\"", ru: 'э', code: 'Quote' },
  { eng: 'z', ru: 'я', code: 'KeyZ' },
  { eng: 'x', ru: 'ч', code: 'KeyX' },
  { eng: 'c', ru: 'с', code: 'KeyC' },
  { eng: 'v', ru: 'м', code: 'KeyV' },
  { eng: 'b', ru: 'и', code: 'KeyB' },
  { eng: 'n', ru: 'т', code: 'KeyN' },
  { eng: 'm', ru: 'ь', code: 'KeyM' },
  { eng: ',<', ru: 'б', code: 'Comma' },
  { eng: '.>', ru: 'ю', code: 'Period' },
  { eng: '/?', ru: '.,', code: 'Slash' },
  { eng: ' ', ru: ' ', code: 'Space' },
];

export const digits = [
  { digit: '1', shift: '!', code: 'Digit1' },
  { digit: '2', shift: '@', code: 'Digit2' },
  { digit: '3', shift: '#', code: 'Digit3' },
  { digit: '4', shift: '$', code: 'Digit4' },
  { digit: '5', shift: '%', code: 'Digit5' },
  { digit: '6', shift: '^', code: 'Digit6' },
  { digit: '7', shift: '&', code: 'Digit7' },
  { digit: '8', shift: '*', code: 'Digit8' },
  { digit: '9', shift: '(', code: 'Digit9' },
  { digit: '0', shift: ')', code: 'Digit0' },
  { digit: '-', shift: '_', code: 'Minus' },
  { digit: '=', shift: '+', code: 'Equal' },
];

export const controls = [
  { value: 'Backspace', code: 'Backspace' },
  { value: 'Tab', code: 'Tab' },
  { value: 'CapsLock', code: 'CapsLock' },
  { value: 'Enter', code: 'Enter' },
  { value: 'Shift', code: 'ShiftLeft' },
  { value: '↑', code: 'ArrowUp' },
  { value: 'Shift', code: 'ShiftRight' },
  { value: 'Ctrl', code: 'ControlLeft' },
  { value: 'Win', code: 'MetaLeft' },
  { value: 'Alt', code: 'AltLeft' },
  { value: 'Alt', code: 'AltRight' },
  { value: 'Ctrl', code: 'ControlRight' },
  { value: '←', code: 'ArrowLeft' },
  { value: '↓', code: 'ArrowDown' },
  { value: '→', code: 'ArrowRight' },
  { value: '', code: 'lang' },
];
